export const COMPETITIONS = [
  {
    id: 'olympiad',
    shortName: 'Olympiad',
    title: 'Microbiology Olympiad',
    category: 'SMA/Sederajat',
    icon: '🏆',
    glowColor: 'cyan',
    description: 'OSN-level competition testing deep understanding of microbiology concepts, from theory to laboratory skills.',
    fullDescription: 'Challenge your microbiology knowledge and laboratory skills in Indonesia\'s most comprehensive high school microbiology competition. Test your skills with analytical questions equivalent to National Science Olympiad (OSN) standards.',
    format: 'Online preliminary exam + offline final practical exam',
    teamSize: 'Individual',
    eligibility: 'Active SMA/MA/SMK students (all grades)',
    requirements: [
      'Active SMA/MA/SMK student (all grades)',
      'Individual participation',
      'Basic understanding of biology/microbiology',
      'Willingness to learn laboratory techniques',
    ],
    benefits: [
      { icon: '🏆', title: 'Total Prize', value: 'Rp 15.000.000+' },
      { icon: '📜', title: 'Certificates', value: 'E-Certificate for all participants' },
      { icon: '🎓', title: 'ITB Exposure', value: 'Experience world-class lab facilities' },
      { icon: '🔬', title: 'Mentorship', value: 'Direct guidance from ITB lecturers' },
    ],
    whyJoin: [
      {
        icon: '📊',
        title: 'OSN-Standard Competition',
        desc: 'Test your knowledge with analytical questions equivalent to National Science Olympiad (OSN) standards.',
      },
      {
        icon: '🧫',
        title: 'Hands-On Laboratory Experience',
        desc: 'Master essential microbiology techniques: Gram staining, optical density reading, spread plate, and streak plate methods.',
      },
      {
        icon: '🦠',
        title: 'Explore Microbial Dark Matter',
        desc: 'Dive deep into the 99% of unculturable microorganisms and discover their hidden potential.',
      },
      {
        icon: '🔭',
        title: 'Path to Research Career',
        desc: 'Identify your potential as a future microbiology researcher with guidance from ITB experts.',
      },
    ],
    timeline: [
      { phase: 'Registration', date: '1 - 31 July 2026', desc: 'Open registration' },
      { phase: 'Preliminary', date: '1 - 16 August 2026', desc: 'Online theory exam' },
      { phase: 'Semifinal', date: '17 - 31 August 2026', desc: 'Online advanced test' },
      { phase: 'Final', date: '14 - 15 November 2026', desc: 'Offline at ITB Campus' },
    ],
    faq: [
      { q: 'What topics are covered?', a: 'General microbiology, microbial physiology, genetics, ecology, virology, immunology, and applied microbiology.' },
      { q: 'Is there a registration fee?', a: 'Free for all participants.' },
      { q: 'How many rounds?', a: 'Two rounds: preliminary (online) and final (onsite at ITB).' },
    ],
  },
  {
    id: 'spc',
    shortName: 'SPC',
    title: 'Science Project Competition',
    category: 'SMA/Sederajat',
    icon: '🔬',
    glowColor: 'emerald',
    description: 'Creative competition for SMA students to develop innovative microbiology-based product prototypes addressing global challenges.',
    fullDescription: 'Transform your microbiology innovations into real-world prototypes and compete for the chance to change the future of sustainability. Develop prototype solutions for global challenges: renewable energy, waste management, and food security using microbiology.',
    format: 'Executive summary -> Full proposal -> Final pitching',
    teamSize: '2-4 members',
    eligibility: 'Active SMA/MA/SMK students (all grades)',
    requirements: [
      'Team of 2-4 members from same or different schools',
      'Active SMA/MA/SMK students',
      'Proposal and video pitch required',
      'Mentor (teacher) recommended',
    ],
    benefits: [
      { icon: '💰', title: 'Total Prize', value: 'Rp 20.000.000+' },
      { icon: '🏅', title: 'Certificates', value: 'E-Certificate + Trophy' },
      { icon: '🚀', title: 'Prototype Development', value: 'Funding support' },
      { icon: '🤝', title: 'Industry Connection', value: 'Networking with experts' },
    ],
    whyJoin: [
      {
        icon: '🌍',
        title: 'Real-World Impact',
        desc: 'Develop prototype solutions for global challenges: renewable energy, waste management, and food security using microbiology.',
      },
      {
        icon: '💡',
        title: 'Innovation Platform',
        desc: 'Transform your creative ideas into tangible products with guidance from ITB researchers and industry professionals.',
      },
      {
        icon: '🔬',
        title: 'Decode Microbial Dark Matter',
        desc: 'Explore the 99% of unculturable microorganisms and unlock their biotechnological potential.',
      },
      {
        icon: '📈',
        title: 'Entrepreneurial Skills',
        desc: 'Learn to pitch your innovation, develop business models, and connect with potential investors.',
      },
    ],
    timeline: [
      { phase: 'Registration', date: '1 - 31 July 2026', desc: 'Open registration' },
      { phase: 'Preliminary', date: '1 - 16 August 2026', desc: 'Executive summary & video' },
      { phase: 'Semifinal', date: '17 - 31 August 2026', desc: 'Full proposal & video' },
      { phase: 'Final', date: '14 - 15 November 2026', desc: 'Final pitching at ITB' },
    ],
    faq: [
      { q: 'What is the theme?', a: '"Decoding the Earth\'s Dark Matter to Orchestrate a Sustainable Future".' },
      { q: 'Can we have a mentor?', a: 'Yes, a teacher/supervisor is recommended but not mandatory.' },
    ],
  },
  {
    id: 'nec',
    shortName: 'NEC',
    title: 'National Essay Competition',
    category: 'S1 Universitas',
    icon: '📝',
    glowColor: 'purple',
    description: 'Platform for S1 students to develop critical thinking and scientific writing on global microbiology issues.',
    fullDescription: 'Showcase your critical thinking and scientific writing skills. Propose innovative microbiological solutions to global sustainability challenges. Open to all S1 students from any major.',
    format: 'Executive summary -> Full paper & poster -> Pitch deck presentation',
    teamSize: '1-2 authors',
    eligibility: 'Active S1 university students (all majors)',
    requirements: [
      'Active S1 student from any major',
      'Individual or team (max 2 authors)',
      'Full paper (8-12 pages) and infographic poster',
      'Indonesian universities only',
    ],
    benefits: [
      { icon: '💵', title: 'Total Prize', value: 'Rp 18.000.000+' },
      { icon: '📜', title: 'Certificates', value: 'E-Certificate + Trophy' },
      { icon: '📰', title: 'Publication', value: 'Opportunity for journal publication' },
      { icon: '🎓', title: 'Research Network', value: 'Connect with academics' },
    ],
    whyJoin: [
      {
        icon: '🌐',
        title: 'Interdisciplinary Approach',
        desc: 'Open to all S1 students from any major - science, engineering, social sciences, or humanities. Your unique perspective matters!',
      },
      {
        icon: '🧠',
        title: 'Critical Thinking Development',
        desc: 'Hone your ability to analyze complex global issues and propose evidence-based microbiological solutions.',
      },
      {
        icon: '✍️',
        title: 'Scientific Writing Excellence',
        desc: 'Master the art of scientific communication and learn to present complex ideas clearly and persuasively.',
      },
      {
        icon: '🏛️',
        title: 'Policy Impact',
        desc: 'Your essay could influence real policy recommendations and contribute to Indonesia\'s sustainable development goals.',
      },
    ],
    timeline: [
      { phase: 'Registration', date: '1 - 31 July 2026', desc: 'Open registration' },
      { phase: 'Preliminary', date: '1 - 16 August 2026', desc: 'Executive summary' },
      { phase: 'Semifinal', date: '17 - 31 August 2026', desc: 'Full paper & poster' },
      { phase: 'Final', date: '14 - 15 November 2026', desc: 'Pitch deck presentation' },
    ],
    faq: [
      { q: 'What is the word limit?', a: 'Full paper: 8-12 pages, excluding references.' },
      { q: 'Can I submit in Indonesian?', a: 'Yes, both English and Indonesian are accepted.' },
    ],
  },
] as const;
