// Data statis untuk timeline, memories, sponsors, dll.

export const TIMELINE_DATA = [
  {
    id: '1',
    phase: 'Registration',
    date: '13 Jul – 8 Aug 2026',
    title: 'MO Registration Batch 1 (Early Bird)',
    desc: 'Open Registration Batch 1 – Early Bird: IDR 75k • IMD Official Website',
    branch: 'MO',
    icon: '🚀',
  },
  {
    id: '2',
    phase: 'Registration',
    date: '19 Jul – 8 Aug 2026',
    title: 'MO Registration Batch 1 (Timeline Page)',
    desc: 'Open Registration Batch 1 (Per Timeline Page) • IMD Official Website',
    branch: 'MO',
    icon: '📋',
  },
  {
    id: '3',
    phase: 'Preliminary',
    date: '19 Jul – 15 Aug 2026',
    title: 'SPC & NEC Preliminary: Registration & Abstract',
    desc: 'Preliminary Stage: Registration & Abstract Submission (Free) • IMD Official Website',
    branch: 'SPC & NEC',
    icon: '📝',
  },
  {
    id: '4',
    phase: 'Registration',
    date: '9 Aug – 31 Aug 2026',
    title: 'MO Registration Batch 2 (Normal)',
    desc: 'Open Registration Batch 2 – Normal: IDR 85k • IMD Official Website',
    branch: 'MO',
    icon: '📋',
  },
  {
    id: '5',
    phase: 'Announcement',
    date: '1 Sep 2026',
    title: 'SPC & NEC Semifinalist Announcement',
    desc: 'Semifinalist Announcement • IMD Official Website',
    branch: 'SPC & NEC',
    icon: '📢',
  },
  {
    id: '6',
    phase: 'Semifinal',
    date: '2 Sep – 7 Sep 2026',
    title: 'SPC & NEC Semifinalist Re-registration',
    desc: 'Semifinalist Re-registration Stage – Fee: IDR 150k • IMD Official Website',
    branch: 'SPC & NEC',
    icon: '✅',
  },
  {
    id: '7',
    phase: 'Semifinal',
    date: '2 Sep – 30 Sep 2026',
    title: 'SPC Stage 2: Proposal & Elevator Pitch',
    desc: 'Stage 2 Work Period: Proposal Writing & Elevator Pitch Video • Asynchronous / Instagram',
    branch: 'SPC',
    icon: '🎬',
  },
  {
    id: '8',
    phase: 'Semifinal',
    date: '2 Sep – 30 Sep 2026',
    title: 'NEC Full Paper Submission',
    desc: 'Full Paper Submission Window • IMD Official Website',
    branch: 'NEC',
    icon: '📄',
  },
  {
    id: '9',
    phase: 'Workshop',
    date: 'Sep 2026 (TBA)',
    title: 'NEC Full Paper Coaching Session',
    desc: 'Full Paper Coaching Session • Zoom Meeting',
    branch: 'NEC',
    icon: '🎓',
  },
  {
    id: '10',
    phase: 'Preliminary',
    date: '3 – 4 Oct 2026',
    title: 'MO Preliminary: System Trial & Technical Meeting',
    desc: 'Preliminary Round System Access Trial & Technical Meeting • Online / Zoom',
    branch: 'MO',
    icon: '💻',
  },
  {
    id: '11',
    phase: 'Announcement',
    date: '11 Oct 2026',
    title: 'SPC & NEC Finalist Announcement',
    desc: 'Finalist Announcement • IMD Official Website',
    branch: 'SPC & NEC',
    icon: '🏅',
  },
  {
    id: '12',
    phase: 'Final',
    date: '12 Oct – 31 Oct 2026',
    title: 'SPC Prototype Development',
    desc: 'Prototype Development Period for Finalists • Asynchronous',
    branch: 'SPC',
    icon: '🔧',
  },
  {
    id: '13',
    phase: 'Final',
    date: '12 Oct – 31 Oct 2026',
    title: 'NEC Final: Pitch Deck & Poster',
    desc: 'Final Stage: Pitch Deck and Poster Digital Submission • IMD Official Website',
    branch: 'NEC',
    icon: '🖼️',
  },
  {
    id: '14',
    phase: 'Preliminary',
    date: '17 Oct 2026',
    title: 'MO Preliminary Round Exam',
    desc: 'Elimination / Preliminary Round Exam (35 T/F Questions) • Online Examination Platform',
    branch: 'MO',
    icon: '✍️',
  },
  {
    id: '15',
    phase: 'Announcement',
    date: '25 Oct 2026',
    title: 'MO Finalist Announcement',
    desc: 'Announcement of Finalists • Online',
    branch: 'MO',
    icon: '🏅',
  },
  {
    id: '16',
    phase: 'Technical Meeting',
    date: '7 Nov 2026',
    title: 'All Branches Final Technical Meeting',
    desc: 'Final Stage Technical Meeting • Online / Zoom Meeting',
    branch: 'All',
    icon: '🎯',
  },
  {
    id: '17',
    phase: 'Final',
    date: '14 Nov 2026',
    title: 'Final Round / Pitching Day',
    desc: 'Final Round / Pitching Day • In-person at ITB Ganesha',
    branch: 'All',
    icon: '🏆',
  },
  {
    id: '18',
    phase: 'Finale',
    date: '15 Nov 2026',
    title: 'Exhibition & Grand Awarding Ceremony',
    desc: 'Exhibition & Grand Awarding Ceremony • In-person at ITB Ganesha',
    branch: 'All',
    icon: '🎉',
  },
];

export const MEMORIES_DATA = [
  { title: 'PetriDish Art 2024', date: '2024', year: '2024', image: '31.png', color: '#6e8efb' },
  { title: 'Awarding Night 2025', date: 'September 2025', year: '2025', image: '32.png', color: '#a777e3' },
  { title: 'Petri Dish Art 2025', date: 'September 2025', year: '2025', image: '28.jpg', color: '#f093fb' },
  { title: 'Exhibition Microverse', date: 'September 2025', year: '2025', image: '27.jpg', color: '#4facfe' },
  { title: 'Art Collaborator', date: 'September 2025', year: '2025', image: '33.png', color: '#6e8efb' },
  { title: 'Exhibition Microverse', date: 'September 2025', year: '2025', image: '25.jpg', color: '#a777e3' },
  { title: 'Exhibition Microverse', date: 'September 2025', image: '24.jpg', color: '#f093fb' },
  { title: 'Exhibition Microverse', date: 'September 2025', image: '22.jpg', color: '#4facfe' },
  { title: 'Exhibition Microverse', date: 'September 2025', image: '23.jpg', color: '#6e8efb' },
  { title: 'Petri Dish Art 2025', date: 'September 2025', year: '2025', image: '30.jpg', color: '#a777e3' },
];

export const MEDIA_PARTNERS = [
  { name: 'Kompas', icon: 'fa-newspaper' },
  { name: 'Detik', icon: 'fa-globe' },
  { name: 'Tempo', icon: 'fa-broadcast-tower' },
  { name: 'CNN Indonesia', icon: 'fa-tv' },
  { name: 'Republika', icon: 'fa-rss' },
  { name: 'Liputan6', icon: 'fa-newspaper' },
  { name: 'Grid Network', icon: 'fa-th' },
  { name: 'Herworld', icon: 'fa-magazine' },
];

export const INDUSTRY_PARTNERS = [
  { name: 'BioFarma', image: '/partners/biofarma.png' },
  { name: 'Kalbe Farma', image: '/partners/kalbe.png' },
  { name: 'Kimia Farma', image: '/partners/kimia-farma.png' },
  { name: 'Nutrifood', image: '/partners/nutrifood.png' },
  { name: 'Indofood', image: '/partners/indofood.png' },
  { name: 'Unilever', image: '/partners/unilever.png' },
  { name: 'Danone', image: '/partners/danone.png' },
  { name: 'Nestle', image: '/partners/nestle.png' },
];

// Powered by logos (placeholder)
export const POWERED_BY = [
  { name: 'Archaea #Eksis', image: '/logo_archaea.svg' },
  { name: 'SITH', image: '/logo-SITH.png' },
  { name: 'ITB', image: '/logo-itb.png' },
  { name: 'IMD', image: '/favicon.svg' },
];

// Mascot placeholders
export const MASCOTS = [
  { id: 'mascot-1', name: 'Microbe Alpha', image: '/5.svg', color: '#6e8efb' },
  { id: 'mascot-2', name: 'Microbe Beta', image: '/2.svg', color: '#a777e3' },
  { id: 'mascot-3', name: 'Microbe Gamma', image: '/3.svg', color: '#f093fb' },
  { id: 'mascot-4', name: 'Microbe Delta', image: '/4.svg', color: '#4facfe' },
];
